name: Windows CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Generate release tag
        id: tag
        run: echo "release_date=1.0.$(date +'%m%d%Y')" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build tools
        run: |
          choco install -y InnoSetup
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          tools: 'tools_mingw'
          set-env: true
          cache: true
      - name: Build
        shell: cmd
        run: |
          set "QT_ROOT=%Qt6_DIR%\..\.."
          dir /s /b "D:\a\big-file-editor\Qt\g++.exe"
          for /d %%i in ("%QT_ROOT%\Tools\mingw*") do set MINGW_PATH=%%i\bin
          if defined MINGW_PATH (
            echo Found MinGW at %MINGW_PATH%
            set "PATH=%MINGW_PATH%;%PATH%"
          ) else (
            echo MinGW not found in %QT_ROOT%\Tools
          )
          qmake big-file-editor.pro
          mingw32-make
          del /q release\*.h release\*.cpp release\*.o
          windeployqt release\big-file-editor.exe

      - name: After build
        run: |
          iscc big-file-editor-installer.iss
          move Output\setupbigfileeditor.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: setupbigfileeditor
          path: setupbigfileeditor.exe

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: setupbigfileeditor.exe
          tag_name: ${{ steps.tag.outputs.release_date }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
