name: Windows CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Generate release tag
        id: tag
        run: echo "release_date=1.0.$(date +'%m%d%Y')" >> $GITHUB_OUTPUT
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build tools
        run: |
          choco install -y InnoSetup qt6-base-dev make
      - name: Build
        shell: cmd
        run: |
          qmake6 big-file-editor.pro
          mingw32-make
          del /q release\*.h release\*.cpp release\*.o
          windeployqt release\big-file-editor.exe

      - name: After build
        run: |
          iscc big-file-editor-installer.iss
          move Output\setupbigfileeditor.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: setupbigfileeditor
          path: setupbigfileeditor.exe

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        with:
          files: setupbigfileeditor.exe
          tag_name: ${{ steps.tag.outputs.release_date }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
