name: Windows CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Generate release tag
        id: tag
        run: echo "::set-output name=release_tag::1.0.${{ github.run_number }}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install build tools
        run: choco install -y InnoSetup qt5-default make #visualstudio2022buildtools windows-sdk-10.1 VisualCppBuildTools vcredist140
      - name: Build
        shell: cmd
        run: |
          SET PATH=%PATH%;C:\Qt\5.15.2\mingw81_64\bin;
          qmake big-file-editor.pro
          make
          del /q release\*.h release\*.cpp release\*.o
          windeployqt release\big-file-editor.exe

      - name: After build
        run: |
          iscc big-file-editor-installer.iss
          move Output\setupbigfileeditor.exe .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: setupbigfileeditor
          path: setupbigfileeditor.exe

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./setupbigfileeditor.exe
          tag_name: ${{ steps.tag.outputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
